kernel:
  image: linuxkit/kernel:5.6.11
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: rngd-oneshot
    image: linuxkit/rngd:v0.8
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: loadmodules
    image: linuxkit/modprobe:v0.8
    command: ["/macos/booter", "load-modules"]
    capabilities: ["all"]
    binds:
      - "/dev:/dev"
      - "/lib:/lib"
      - "/macos:/macos"
  - name: setupnat
    image: linuxkit/ip:v0.8
    command: ["/macos/booter", "setup-nat"]
    capabilities: ["all"]
    binds:
      - "/dev:/dev"
      - "/macos:/macos"
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  # - name: metadata
  #   image: linuxkit/metadata:v0.8
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
      - INSECURE=true
  - name: acpid
    image: linuxkit/acpid:v0.8
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: ntpd
    image: linuxkit/openntpd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "-f", "/dhcpcd.conf"]
  - name: sshd
    image: linuxkit/sshd:v0.8
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /run:/run
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /usr/bin/ctr:/usr/bin/ctr
      - /usr/bin/runc:/usr/bin/runc
      - /containers:/containers
      - /var/log:/var/log
      - /dev:/dev
      - /sys:/sys
      - /lib:/lib
      - /macos:/macos
      - /macos/sshkeys:/root/.ssh/authorized_keys:ro
      # - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
  - name: qemu
    image: tianon/qemu:5.1.0
    command: ["/macos/booter", "run-qemu"]
    capabilities: ["all"]
    binds:
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/kvm:/dev/kvm"
      - "/dev/sdb:/dev/sdb"
      - "/dev/net/tun:/dev/net/tun"
      - "/dev/vhost-net:/dev/vhost-net"
      - "/macos:/macos"
files:
  - path: "/macos/sshkeys"
    source: "~/.ssh/id_rsa.pub"
    mode: "0400"
  - path: etc/linuxkit-config
    metadata: yaml
  - path: "macos/bootloader.img"
    source: "@BOOTLOADER@"
    mode: "0666"
  - path: "macos/booter"
    source: "@MACOS_BOOT@"
    mode: "0555"
trust:
  org:
    - linuxkit
    - library
